/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import org.junit.Before;
import org.junit.Test;

import java.io.ByteArrayOutputStream;
import java.io.FileNotFoundException;
import java.io.PrintStream;

import static org.junit.Assert.*;

public class AppTest {

  @Test public void testGetRandomQuote() throws FileNotFoundException {
    Quote[] quotes = App.getQuotesFromFile();
    App.getRandomQuote(quotes);
    assertNotEquals("Should contain a quote", "", App.getRandomQuote(quotes));
  }

  @Test public void testGetQuoteFromAPI(){

  }
}
