/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;


import org.junit.Before;
import org.junit.Test;

import java.io.ByteArrayOutputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.PrintStream;

import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertTrue;

public class AppTest {

  // https://stackoverflow.com/questions/1119385/junit-test-for-system-out-println
  private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();

  @Before
  public void setUpStreams() {
    System.setOut(new PrintStream(outContent));
  }

  @Test public void testGetRandomQuoteFromFile_not_empty() throws FileNotFoundException {
    Quote[] quotes = App.makeQuotesFromFile();
    App.getRandomQuoteFromFile(quotes);
    assertNotEquals("Should contain a quote", "", App.getRandomQuoteFromFile(quotes));
  }

  @Test public void testGetRandomQuoteFromFile() throws FileNotFoundException {
    Quote[] quotes = App.makeQuotesFromFile();
    String result = App.getRandomQuoteFromFile(quotes).toString();
    String regex ="[^“].*[”] - .*";
    assertTrue("Should contain a regex test of true", result.matches(regex));
  }

  @Test public void testGetQuoteFromApi_not_empty() throws FileNotFoundException {
    App.getQuoteFromAPI();
    String result = outContent.toString();
    assertNotEquals("Should contain a quote", "", result);
  }

  @Test public void testGetQuoteFromApi() throws FileNotFoundException {
    App.getQuoteFromAPI();
    String result = outContent.toString();
    assertTrue("Should contain a quote", result.contains("-") || result.contains("?"));

  }

}

  
