/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

/*
Your program should use GSON to parse the .json file.
The app needs no functionality other than showing
random quote and the author when it is run.
The app should choose one quote each time it is run.
 */
public class App {
    public static void main(String[] args){
//        Gson gson = new Gson();
    }
}
