/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {
  public static void main(String[] args) throws FileNotFoundException {
    getRandomQuote();
  }

  public static void getRandomQuote() throws FileNotFoundException {
    String allQuotes = readFile("src/main/resources/recentquotes.json");
    Gson gson = new Gson();
    Quote[] quotes = gson.fromJson(allQuotes, Quote[].class);
    int random = (int)(Math.random() * quotes.length);
    System.out.println(quotes[random].toString());
  }

  public static String readFile(String fileName) throws FileNotFoundException {
    Scanner q = new Scanner(new File(fileName));
    StringBuilder quoteStrings = new StringBuilder();
    while(q.hasNextLine()){
      quoteStrings.append(q.nextLine());
    }
    return quoteStrings.toString();
  }

}
